#!/usr/bin/env bash
set -e # halt script on error
echo "build: " > build.yml
echo $COMMIT_REF >> build.yml
if [ "$BRANCH" = "master" ]; then
    bundle exec jekyll build --config _config/develop.yml,build.yml
else
    bundle exec jekyll build --config _config.yml,build.yml
fi
#bundle exec htmlproofer _site --disable-external --assume-extension --file-ignore /apigen/ --url-ignore /draft, /drafts, /models
