process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
const axios = require('axios')
const fs = require('fs')
const yamlDir = './nuxt/assets/config/'

const ax = axios.create({
  baseURL: process.env.FS_DATA,
  timeout: 5000
})

const version = fs.readFileSync('./version', "utf8").trim();

const items = [
  'versions',
  'patterns',
  'measurements',
  'mapping',
  'namespaces'
]

fetch(items)

function fetch(items) {
  return new Promise(function(resolve, reject) {
    const promises = []
    for( let index in items) {
      let topic = items[index]
      console.log('Loading '+topic)
      promises.push(
        ax.get('/config/'+topic, { headers: {'Freesewing-Site-Version': version} })
        .then((res) => {
          console.log('Writing '+topic)
          fs.writeFileSync(yamlDir+topic+'.yaml', "# This file was auto-generated by `npm run configure`\n"+res.data, 'utf8')
        })
        .catch((error) => {
          console.log('Loading '+topic+' failed')
          console.log(error)
        })
        )
      }
      Promise.all(promises)
      .then(() => {
        console.log('All done')
        resolve(true)
      })
    .catch(() => { reject(false) })
  })
}

